-- apply changes
create table url (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  created_at                    timestamp not null,
  constraint pk_url primary key (id)
);

create table site_check (
  id                            bigint generated by default as identity not null,
  url_id                        bigint not null,
  title                         varchar(255),
  h1                            varchar(255),
  description                   varchar(255),
  checking_date                 timestamp not null,
  constraint pk_site_check primary key (id)
);

