ebean:
  ddl:
    run: true
    generate: true
#  dbSchema: ${DB}
#  migration:
#    run: true       # run database migrations on startup

datasource:
  default: ${DB}

  production:
    platform: postgresql
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${URL}

  development:
    username: sa
    password: sa
    url: jdbc:h2:mem:testDB
#    url: jdbc:h2:tcp://localhost/~/myTemp/DB/test
#    url: jdbc:h2:~/myTemp/DB/tes6
