ebean:
#  ddl:
#    run: true
#    generate: true
#  dbSchema: ${DB}
  migration:
    run: true       # run database migrations on startup

datasource:
  default: ${DB}

  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: jdbc:${DATABASE_URL}

  development:
    username: sa
    password: sa
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:tcp://localhost/~/myTemp/DB/test
    url: jdbc:h2:~/myTemp/DB/test1
