ebean:
  dbSchema: sa  # use this schema rather than public
  migration:
    run: true       # run database migrations on startup

datasource:
  db:
    username: sa
    password: sa
    url: jdbc:h2:~/test

  otherDBPostgresSQL:
    username: other_username
    password: ${otherPassword}
    url: jdbc:postgresql://${otherDatabaseHost}:5432/other_dbname
