ebean:
  ddl:
    run: true
    generate: true
#  dbSchema: ${APP_ENV}
#  migration:
#    run: true       # run database migrations on startup
#    generate: true

datasource:
  default: ${APP_ENV}

  production:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  development:
    username: sa
    password: sa
    url: jdbc:h2:mem:testDB
#    url: jdbc:h2:tcp://localhost/~/myTemp/DB/test
#    url: jdbc:h2:~/myTemp/DB/tes6
