/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import io.javalin.Javalin;

public final class App {
    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7070);
        app.get("/", ctx -> ctx.result("I Love You!!! \nAnd now I can do it!!!"));
    }
}

